src/Entity/Factuur.php
<?php

namespace App\Entity;

use App\Repository\FactuurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FactuurRepository::class)
 */
class Factuur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $factuur_datum;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="factuurs")
     */
    private $User_id;

    /**
     * @ORM\OneToMany(targetEntity=FactuurRegel::class, mappedBy="Factuur_id")
     */
    private $factuurRegels;

    public function __construct()
    {
        $this->factuurRegels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFactuurDatum(): ?\DateTimeInterface
    {
        return $this->factuur_datum;
    }

    public function setFactuurDatum(\DateTimeInterface $factuur_datum): self
    {
        $this->factuur_datum = $factuur_datum;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->User_id;
    }

    public function setUserId(?User $User_id): self
    {
        $this->User_id = $User_id;

        return $this;
    }

    /**
     * @return Collection|FactuurRegel[]
     */
    public function getFactuurRegels(): Collection
    {
        return $this->factuurRegels;
    }

    public function addFactuurRegel(FactuurRegel $factuurRegel): self
    {
        if (!$this->factuurRegels->contains($factuurRegel)) {
            $this->factuurRegels[] = $factuurRegel;
            $factuurRegel->setFactuurId($this);
        }

        return $this;
    }

    public function removeFactuurRegel(FactuurRegel $factuurRegel): self
    {
        if ($this->factuurRegels->contains($factuurRegel)) {
            $this->factuurRegels->removeElement($factuurRegel);
            // set the owning side to null (unless already changed)
            if ($factuurRegel->getFactuurId() === $this) {
                $factuurRegel->setFactuurId(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->id.' -> '.$this->getId();
    }
}

src/Form/FactuurType.php
<?php

namespace App\Form;

use App\Entity\Factuur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FactuurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('factuur_datum')
            ->add('User_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Factuur::class,
        ]);
    }
}

src/Controller/FactuurController.php
<?php

namespace App\Controller;

use App\Entity\Factuur;
use App\Form\FactuurType;
use App\Repository\FactuurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/factuur")
 */
class FactuurController extends AbstractController
{
    /**
     * @Route("/", name="factuur_index", methods={"GET"})
     */
    public function index(FactuurRepository $factuurRepository): Response
    {
        return $this->render('factuur/index.html.twig', [
            'factuurs' => $factuurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="factuur_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $factuur = new Factuur();
        $form = $this->createForm(FactuurType::class, $factuur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($factuur);
            $entityManager->flush();

            return $this->redirectToRoute('factuur_index');
        }

        return $this->render('factuur/new.html.twig', [
            'factuur' => $factuur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="factuur_show", methods={"GET"})
     */
    public function show(Factuur $factuur): Response
    {
        return $this->render('factuur/show.html.twig', [
            'factuur' => $factuur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="factuur_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Factuur $factuur): Response
    {
        $form = $this->createForm(FactuurType::class, $factuur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('factuur_index');
        }

        return $this->render('factuur/edit.html.twig', [
            'factuur' => $factuur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="factuur_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Factuur $factuur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$factuur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($factuur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('factuur_index');
    }
}

templates/factuur/_delete_form.html.twig
<form method="post" action="{{ path('factuur_delete', {'id': factuur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ factuur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/factuur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/factuur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Factuur{% endblock %}

{% block body %}
    <h1>Edit Factuur</h1>

    {{ include('factuur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('factuur_index') }}">back to list</a>

    {{ include('factuur/_delete_form.html.twig') }}
{% endblock %}

templates/factuur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Factuur index{% endblock %}

{% block body %}
    <h1>Factuur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Factuur_datum</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for factuur in factuurs %}
            <tr>
                <td>{{ factuur.id }}</td>
                <td>{{ factuur.factuurDatum ? factuur.factuurDatum|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('factuur_show', {'id': factuur.id}) }}">show</a>
                    <a href="{{ path('factuur_edit', {'id': factuur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('factuur_new') }}">Create new</a>
{% endblock %}

templates/factuur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Factuur{% endblock %}

{% block body %}
    <h1>Create new Factuur</h1>

    {{ include('factuur/_form.html.twig') }}

    <a href="{{ path('factuur_index') }}">back to list</a>
{% endblock %}

templates/factuur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Factuur{% endblock %}

{% block body %}
    <h1>Factuur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ factuur.id }}</td>
            </tr>
            <tr>
                <th>Factuur_datum</th>
                <td>{{ factuur.factuurDatum ? factuur.factuurDatum|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('factuur_index') }}">back to list</a>

    <a href="{{ path('factuur_edit', {'id': factuur.id}) }}">edit</a>

    {{ include('factuur/_delete_form.html.twig') }}
{% endblock %}