src/Entity/Meno.php
<?php

namespace App\Entity;

use App\Repository\MenoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MenoRepository::class)
 */
class Meno
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="menos")
     */
    private $User_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->User_id;
    }

    public function setUserId(?User $User_id): self
    {
        $this->User_id = $User_id;

        return $this;
    }
}

src/Form/MenoType.php
<?php

namespace App\Form;

use App\Entity\Meno;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MenoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('updated_at')
            ->add('User_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Meno::class,
        ]);
    }
}

src/Controller/MenoController.php
<?php

namespace App\Controller;

use App\Entity\Meno;
use App\Form\MenoType;
use App\Repository\MenoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/meno")
 */
class MenoController extends AbstractController
{
    /**
     * @Route("/", name="meno_index", methods={"GET"})
     */
    public function index(MenoRepository $menoRepository): Response
    {
        return $this->render('meno/index.html.twig', [
            'menos' => $menoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="meno_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $meno = new Meno();
        $form = $this->createForm(MenoType::class, $meno);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($meno);
            $entityManager->flush();

            return $this->redirectToRoute('meno_index');
        }

        return $this->render('meno/new.html.twig', [
            'meno' => $meno,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="meno_show", methods={"GET"})
     */
    public function show(Meno $meno): Response
    {
        return $this->render('meno/show.html.twig', [
            'meno' => $meno,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="meno_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Meno $meno): Response
    {
        $form = $this->createForm(MenoType::class, $meno);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('meno_index');
        }

        return $this->render('meno/edit.html.twig', [
            'meno' => $meno,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="meno_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Meno $meno): Response
    {
        if ($this->isCsrfTokenValid('delete'.$meno->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($meno);
            $entityManager->flush();
        }

        return $this->redirectToRoute('meno_index');
    }
}

templates/meno/_delete_form.html.twig
<form method="post" action="{{ path('meno_delete', {'id': meno.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ meno.id) }}">
    <button class="btn">Delete</button>
</form>

templates/meno/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/meno/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Meno{% endblock %}

{% block body %}
    <h1>Edit Meno</h1>

    {{ include('meno/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('meno_index') }}">back to list</a>

    {{ include('meno/_delete_form.html.twig') }}
{% endblock %}

templates/meno/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Meno index{% endblock %}

{% block body %}
    <h1>Meno index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Content</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for meno in menos %}
            <tr>
                <td>{{ meno.id }}</td>
                <td>{{ meno.title }}</td>
                <td>{{ meno.content }}</td>
                <td>{{ meno.updatedAt ? meno.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('meno_show', {'id': meno.id}) }}">show</a>
                    <a href="{{ path('meno_edit', {'id': meno.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('meno_new') }}">Create new</a>
{% endblock %}

templates/meno/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Meno{% endblock %}

{% block body %}
    <h1>Create new Meno</h1>

    {{ include('meno/_form.html.twig') }}

    <a href="{{ path('meno_index') }}">back to list</a>
{% endblock %}

templates/meno/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Meno{% endblock %}

{% block body %}
    <h1>Meno</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ meno.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ meno.title }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ meno.content }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ meno.updatedAt ? meno.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('meno_index') }}">back to list</a>

    <a href="{{ path('meno_edit', {'id': meno.id}) }}">edit</a>

    {{ include('meno/_delete_form.html.twig') }}
{% endblock %}